
package practico4;

import java.util.HashSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Cetera Evelyn
 */
public class FormularioInscripcion extends javax.swing.JInternalFrame {

        HashSet<Alumno> alumnos;
        HashSet<Materia> materias;
    /**
     * Creates new form FormularioInscripcion
     * @param alumno
     * @param materia
     */
    public FormularioInscripcion(HashSet<Alumno> alumno, HashSet<Materia> materia) {
        initComponents();
        this.alumnos = alumno;
        this.materias = materia;
        
        for (Alumno a : alumno) {
            jComboBoxAlumno.addItem(a);
        }
        for (Materia m : materia) {
            jComboBoxMateria.addItem(m);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTituloInscripcion = new javax.swing.JLabel();
        jLabelMateria = new javax.swing.JLabel();
        jLabelAlumno = new javax.swing.JLabel();
        jComboBoxMateria = new javax.swing.JComboBox<>();
        jComboBoxAlumno = new javax.swing.JComboBox<>();
        jButtonInscribir = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        jLabelTituloInscripcion.setText("Formulario de Inscripción");

        jLabelMateria.setText("Elija una materia: ");

        jLabelAlumno.setText("Elija un alumno:");

        jButtonInscribir.setText("Inscribir");
        jButtonInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInscribirActionPerformed(evt);
            }
        });

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMateria)
                            .addComponent(jLabelAlumno))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxMateria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxAlumno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jButtonInscribir)
                        .addGap(29, 29, 29)
                        .addComponent(jButtonSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabelTituloInscripcion)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloInscripcion)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMateria)
                    .addComponent(jComboBoxMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAlumno)
                    .addComponent(jComboBoxAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInscribir)
                    .addComponent(jButtonSalir))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here - SALIR:
        dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInscribirActionPerformed
        // TODO add your handling code here - INSCRIBIR:
        Alumno alu = (Alumno) jComboBoxAlumno.getSelectedItem();
        Materia mat = (Materia) jComboBoxMateria.getSelectedItem();
        
        if(alu != null && mat != null){
            alu.agregarMateria(mat);
            JOptionPane.showMessageDialog(this, "Alumno inscripto correctamente");
        }
        jComboBoxAlumno.setSelectedIndex(-1);
        jComboBoxMateria.setSelectedIndex(-1);
        
    }//GEN-LAST:event_jButtonInscribirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInscribir;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JComboBox<Alumno> jComboBoxAlumno;
    private javax.swing.JComboBox<Materia> jComboBoxMateria;
    private javax.swing.JLabel jLabelAlumno;
    private javax.swing.JLabel jLabelMateria;
    private javax.swing.JLabel jLabelTituloInscripcion;
    // End of variables declaration//GEN-END:variables
}
