
package practico4;


import java.util.HashSet;

/**
 *
 * @author Cetera Evelyn
 */
public class GestionDeInscripciones extends javax.swing.JFrame {

        private static HashSet<Alumno> alumnos;
        private static HashSet<Materia> materias;
    /**
     * Creates new form GestionDeInscripciones
     */
    public GestionDeInscripciones() {
        initComponents();
        alumnos = new HashSet<>();
        materias = new HashSet<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpEscritorio = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmAlumnos = new javax.swing.JMenu();
        jmiAgregarAlumno = new javax.swing.JMenuItem();
        jmMaterias = new javax.swing.JMenu();
        jMenuItemAgregarMateria = new javax.swing.JMenuItem();
        jmRegistro = new javax.swing.JMenu();
        jMenuItemInscripciones = new javax.swing.JMenuItem();
        jMenuItemListarInscripciones = new javax.swing.JMenuItem();
        jmSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Desktop");

        jdpEscritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpEscritorioLayout = new javax.swing.GroupLayout(jdpEscritorio);
        jdpEscritorio.setLayout(jdpEscritorioLayout);
        jdpEscritorioLayout.setHorizontalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpEscritorioLayout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jdpEscritorioLayout.setVerticalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpEscritorioLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addContainerGap(400, Short.MAX_VALUE))
        );

        jmAlumnos.setText("Alumnos");

        jmiAgregarAlumno.setText("Agregar Alumno");
        jmiAgregarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAgregarAlumnoActionPerformed(evt);
            }
        });
        jmAlumnos.add(jmiAgregarAlumno);

        jMenuBar1.add(jmAlumnos);

        jmMaterias.setText("Materias");

        jMenuItemAgregarMateria.setText("Agregar Materia");
        jMenuItemAgregarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgregarMateriaActionPerformed(evt);
            }
        });
        jmMaterias.add(jMenuItemAgregarMateria);

        jMenuBar1.add(jmMaterias);

        jmRegistro.setText("Registro");

        jMenuItemInscripciones.setText("Inscripciones");
        jMenuItemInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInscripcionesActionPerformed(evt);
            }
        });
        jmRegistro.add(jMenuItemInscripciones);

        jMenuItemListarInscripciones.setText("Listar Inscripciones");
        jMenuItemListarInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarInscripcionesActionPerformed(evt);
            }
        });
        jmRegistro.add(jMenuItemListarInscripciones);

        jMenuBar1.add(jmRegistro);

        jmSalir.setText("Salir");
        jmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(jmSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdpEscritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jdpEscritorio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSalirActionPerformed
        // TODO add your handling code here - BOTON SALIR:
        System.exit(0);
    }//GEN-LAST:event_jmSalirActionPerformed

    private void jMenuItemInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInscripcionesActionPerformed
        // TODO add your handling code here INTERNAL FRAME - INSCRIPCIONES:
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        FormularioInscripcion vfi = new FormularioInscripcion(alumnos, materias);
        vfi.setVisible(true);
        jdpEscritorio.add(vfi);
        jdpEscritorio.moveToFront(vfi);
        
        
    }//GEN-LAST:event_jMenuItemInscripcionesActionPerformed

    private void jmiAgregarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAgregarAlumnoActionPerformed
        // TODO add your handling code here INTERNAL FRAME - ALUMNO:
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        AltaAlumno vaa = new AltaAlumno(alumnos);
        vaa.setVisible(true);
        jdpEscritorio.add(vaa);
        jdpEscritorio.moveToFront(vaa);
        
    }//GEN-LAST:event_jmiAgregarAlumnoActionPerformed

    private void jMenuItemAgregarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgregarMateriaActionPerformed
        // TODO add your handling code here INTERNAL FRAME - MATERIA:
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        AltaMateria vam = new AltaMateria(materias);
        vam.setVisible(true);
        jdpEscritorio.add(vam);
        jdpEscritorio.moveToFront(vam);
    }//GEN-LAST:event_jMenuItemAgregarMateriaActionPerformed

    private void jMenuItemListarInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarInscripcionesActionPerformed
        // TODO add your handling code here - LISTAR INSCRIPCIONES :
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        CantidadInscripciones vci = new CantidadInscripciones(alumnos, materias);
        vci.setVisible(true);
        jdpEscritorio.add(vci);
        jdpEscritorio.moveToFront(vci);
    }//GEN-LAST:event_jMenuItemListarInscripcionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionDeInscripciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionDeInscripciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionDeInscripciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionDeInscripciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionDeInscripciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAgregarMateria;
    private javax.swing.JMenuItem jMenuItemInscripciones;
    private javax.swing.JMenuItem jMenuItemListarInscripciones;
    private javax.swing.JDesktopPane jdpEscritorio;
    private javax.swing.JMenu jmAlumnos;
    private javax.swing.JMenu jmMaterias;
    private javax.swing.JMenu jmRegistro;
    private javax.swing.JMenu jmSalir;
    private javax.swing.JMenuItem jmiAgregarAlumno;
    // End of variables declaration//GEN-END:variables
}


